import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { lstat, readFile, realpath } from "node:fs/promises";
import { dirname, join, normalize, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { isStrictBoundedSemver } from "./src/runtime/strict-semver.mjs";

export const NORMAL_PLUGIN_NAME = "Knowledge Workbench";
export const ACCEPTANCE_PLUGIN_NAME = "Knowledge Workbench (Read-only acceptance)";
export const PLUGIN_ID = "knowledge-workbench";

const NODE_EXTERNALS = [...new Set(
  builtinModules.flatMap((name) => [
    name,
    name.startsWith("node:") ? name.slice(5) : `node:${name}`,
  ]),
)];
const EXTERNAL_MODULES = Object.freeze([
  "obsidian",
  "electron",
  "@codemirror/state",
  "@codemirror/view",
  ...NODE_EXTERNALS,
]);
const BANNER = "/* Generated by esbuild from the Knowledge Workbench TypeScript source. */";

export { isStrictBoundedSemver as isBoundedSemver };

function expectedForMode(mode, version) {
  if (mode === "normal") {
    return {
      entrySuffix: normalize("src/main.ts"),
      manifestName: NORMAL_PLUGIN_NAME,
      artifactBinding: `${PLUGIN_ID}@${version}:normal`,
    };
  }
  if (mode === "read-only-acceptance") {
    return {
      entrySuffix: normalize("src/main-acceptance.ts"),
      manifestName: ACCEPTANCE_PLUGIN_NAME,
      artifactBinding: `${PLUGIN_ID}@${version}:read-only-acceptance`,
    };
  }
  throw new Error("Build mode must be exactly normal or read-only-acceptance");
}

function buildOptions({
  entryPoint,
  outfile,
  mode,
  pluginVersion,
  manifestName,
  artifactBinding,
  production,
  metafile = false,
  write = true,
}) {
  if (!isStrictBoundedSemver(pluginVersion)) throw new Error("pluginVersion must be a bounded semantic version");
  if (typeof entryPoint !== "string" || entryPoint.length === 0) throw new Error("entryPoint is required");
  if (typeof outfile !== "string" || outfile.length === 0) throw new Error("outfile is required");
  if (typeof production !== "boolean") throw new Error("production must be a boolean");
  if (typeof metafile !== "boolean") throw new Error("metafile must be a boolean");
  if (typeof write !== "boolean") throw new Error("write must be a boolean");
  const expected = expectedForMode(mode, pluginVersion);
  const normalizedEntry = normalize(entryPoint);
  if (normalizedEntry !== expected.entrySuffix && !normalizedEntry.endsWith(`${normalize("/")}${expected.entrySuffix}`)) {
    throw new Error(`entryPoint does not match ${mode} mode`);
  }
  if (manifestName !== expected.manifestName) throw new Error(`manifestName does not match ${mode} mode`);
  if (artifactBinding !== expected.artifactBinding) throw new Error(`artifactBinding does not match ${mode} mode`);
  return {
    banner: { js: BANNER },
    entryPoints: [entryPoint],
    bundle: true,
    define: {
      __KNOWLEDGE_WORKBENCH_BUILD_MODE__: JSON.stringify(mode),
      __KNOWLEDGE_WORKBENCH_PLUGIN_VERSION__: JSON.stringify(pluginVersion),
      __KNOWLEDGE_WORKBENCH_MANIFEST_NAME__: JSON.stringify(manifestName),
      __KNOWLEDGE_WORKBENCH_ARTIFACT_BINDING__: JSON.stringify(artifactBinding),
    },
    external: EXTERNAL_MODULES,
    format: "cjs",
    target: "es2021",
    logLevel: "silent",
    sourcemap: production ? false : "inline",
    treeShaking: true,
    outfile,
    minify: production,
    metafile,
    write,
  };
}

export async function buildBundle(options) {
  return esbuild.build(buildOptions(options));
}

async function readNormalBuildIdentity(repoRoot) {
  const rootStat = await lstat(repoRoot);
  if (!rootStat.isDirectory() || rootStat.isSymbolicLink() || await realpath(repoRoot) !== repoRoot) {
    throw new Error("Repository root must be a canonical non-symlink directory");
  }
  let manifest;
  let packageJson;
  try {
    manifest = JSON.parse(await readFile(join(repoRoot, "manifest.json"), "utf8"));
    packageJson = JSON.parse(await readFile(join(repoRoot, "package.json"), "utf8"));
  } catch {
    throw new Error("Normal build manifest.json and package.json must be valid JSON");
  }
  if (manifest?.id !== PLUGIN_ID || manifest?.name !== NORMAL_PLUGIN_NAME) {
    throw new Error("Normal build manifest identity does not match Knowledge Workbench");
  }
  if (!isStrictBoundedSemver(manifest.version) || manifest.version !== packageJson?.version) {
    throw new Error("Normal build package and manifest versions must match a bounded semantic version");
  }
  return { version: manifest.version, name: manifest.name };
}

async function runCli() {
  const environment = process.argv[2] ?? "development";
  const mode = process.argv[3] ?? "normal";
  if (environment !== "development" && environment !== "production") {
    throw new Error("Build environment must be exactly development or production");
  }
  if (mode !== "normal") throw new Error("The direct esbuild CLI only supports normal mode");
  const repoRoot = await realpath(dirname(fileURLToPath(import.meta.url)));
  const identity = await readNormalBuildIdentity(repoRoot);
  const options = {
    entryPoint: join(repoRoot, "src", "main.ts"),
    outfile: join(repoRoot, "main.js"),
    mode: "normal",
    pluginVersion: identity.version,
    manifestName: identity.name,
    artifactBinding: `${PLUGIN_ID}@${identity.version}:normal`,
    production: environment === "production",
    metafile: false,
  };
  if (environment === "production") {
    await buildBundle(options);
    return;
  }
  const context = await esbuild.context(buildOptions(options));
  await context.watch();
}

const invokedUrl = process.argv[1] === undefined ? null : pathToFileURL(resolve(process.argv[1])).href;
if (invokedUrl === import.meta.url) {
  try {
    await runCli();
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  }
}
